###############-VERSION-####################
version: '3.4'
##############-SERVICES-####################
services:
  example-app:
    build: /home/bluxterz/Desktop/Tarea2/bd
    container_name: example-app
    volumes:
      - /home/bluxterz/Desktop/Tarea2/bd:/usr/src/app  # Ruta absoluta a tu código fuente

  db:
    container_name: db
    image: postgres:16.0-alpine3.18
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Ruta relativa al archivo init.sql en la misma ubicación que el archivo docker-compose.yml


###################-PG_ADMIN-##########################
  pgadmin:
    image: "dpage/pgadmin4"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "81:80"
    depends_on:
      - db
    logging:
      driver: none