version: '3.8'

services:
  hadoop:
    container_name: hadoop
    build:
      context: ./Hadoop/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./Hadoop/examples:/home/hduser/examples
      - ./Hadoop/buscador:/home/hduser/buscador
    ports:
      - 9864:9864
      - 9870:9870
      - 8088:8088
      - 9000:9000
      - 8020:8020
    
  mysql:
    image: 'mysql:latest'
    container_name: mysql
    restart: always
    ports:
      - "4306:3306"
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      - TZ=America/Santiago
      - MYSQL_ROOT_PASSWORD=db
      - MYSQL_DATABASE=tarea3
    volumes:
      -  ./bd-mysql:/var/lib/mysql
      -  ./sql/schema.sql:/docker-entrypoint-initdb.d/1.sql